### ISSUE TITLE
引用リツイート元のアカウント名にマウスカーソルをホバーしたときのポップアップがchannelsの後ろに隠れる

### ISSUE THREAD

**Issue by Rytaryu** [nyanko3141592/fakeLookTwitter#11]
実際の例：![bug](https://user-images.githubusercontent.com/53173674/216247662-cd103574-c0f0-4b55-8f93-4545ee575f96.png)

環境
・OS：Windows11
・ブラウザ：Brave ver.1.47.186 (Chromium: 109.0.5414.119)
・Twitterテーマ：ブラック

**Comment by nyanko3141592** [comment]
Duplicate of #1
